# Generated by Django 3.1.5 on 2021-03-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
    ]
